export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  GOOGLE_CALLBACK: '/auth/google/callback',
  DASHBOARD: '/dashboard',
  AI_TUTOR: '/ai-tutor',
  NOTES: '/notes',
  PDF_CHAT: '/pdf-chat',
  FLASHCARDS: '/flashcards',
  QUIZ: '/quiz',
  ATTENDANCE: '/attendance',
  STUDY_PLANNER: '/study-planner',
  COMMUNITY: '/community',
  CLINICAL_CASES: '/clinical-cases',
  ANALYTICS: '/analytics',
  PROFILE: '/profile',
  SETTINGS: '/settings',
} as const

export const NAV_ITEMS = [
  { label: 'Dashboard', path: ROUTES.DASHBOARD, icon: 'LayoutDashboard' },
  { label: 'AI Tutor', path: ROUTES.AI_TUTOR, icon: 'Bot' },
  { label: 'Notes', path: ROUTES.NOTES, icon: 'NotebookPen' },
  { label: 'PDF Chat', path: ROUTES.PDF_CHAT, icon: 'FileText' },
  { label: 'Flashcards', path: ROUTES.FLASHCARDS, icon: 'Layers' },
  { label: 'Quiz', path: ROUTES.QUIZ, icon: 'HelpCircle' },
  { label: 'Attendance', path: ROUTES.ATTENDANCE, icon: 'CalendarCheck' },
  { label: 'Study Planner', path: ROUTES.STUDY_PLANNER, icon: 'Calendar' },
  { label: 'Community', path: ROUTES.COMMUNITY, icon: 'Users' },
  { label: 'Clinical Cases', path: ROUTES.CLINICAL_CASES, icon: 'Stethoscope' },
  { label: 'Analytics', path: ROUTES.ANALYTICS, icon: 'BarChart3' },
] as const
